name = "starnav"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "NAV_DB"
database_name = "book"
database_id = "adf4261f-e0e4-4f9c-a956-7c9b33bb78c9"

[[kv_namespaces]]
binding = "NAV_AUTH"
id = "615f91099a114448998117f82dc72168"
